name: Run isort

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: isort/isort-action@master
        with:
            isortVersion: 5.13.2

